export interface Category {
  id: number;
  slug: string;
  name: string;
  description: string;
  count: number;
}

export const categories: Category[] = [
  {
    id: 88,
    slug: `export`,
    name: `Export`,
    description: ``,
    count: 10,
  },
  {
    id: 39,
    slug: `biotech`,
    name: `Biotech`,
    description: `Focusing on biotech startups, biopharma innovations, bioengineering, and transformative life sciences trends.`,
    count: 8,
  },
  {
    id: 43,
    slug: `defense`,
    name: `Defense`,
    description: `Coverage of security technologies, defense innovations, autonomous systems, and safeguarding societies worldwide.`,
    count: 7,
  },
  {
    id: 60,
    slug: `nuclear`,
    name: `Nuclear`,
    description: `Reporting on nuclear technologies, clean energy advancements, fusion research, policy trends, and nuclear’s role in global security.`,
    count: 7,
  },
  {
    id: 59,
    slug: `medtech`,
    name: `Med Tech`,
    description: `Focusing on medical technology innovations, healthcare devices, surgical tools, and digital health transformations.`,
    count: 6,
  },
  {
    id: 61,
    slug: `medicine`,
    name: `Precision Medicine`,
    description: `Covering personalized medical treatments, genomic therapies, data-driven healthcare, and patient-centered innovation.`,
    count: 6,
  },
  {
    id: 48,
    slug: `energy`,
    name: `Energy & Sustainability`,
    description: `Exploring clean energy breakthroughs, sustainability innovations, climate solutions, and responsible resource use.`,
    count: 5,
  },
  {
    id: 36,
    slug: `manufacturing`,
    name: `Manufacturing`,
    description: `Exploring cutting-edge production methods, smart factories, and innovations reshaping how we build the future.`,
    count: 5,
  },
  {
    id: 66,
    slug: `ai`,
    name: `Technology & AI`,
    description: `Covering artificial intelligence advancements, emerging tech trends, machine learning breakthroughs, and digital transformation.`,
    count: 5,
  },
  {
    id: 57,
    slug: `lifesciences`,
    name: `Life Sciences`,
    description: `Insights into biomedical research, pharmaceutical breakthroughs, clinical advancements, and transformative healthcare solutions.`,
    count: 4,
  },
  {
    id: 42,
    slug: `cybersecurity`,
    name: `Cybersecurity`,
    description: `Reporting on digital resilience, cyber defense strategies, and securing critical infrastructure in a connected world.`,
    count: 3,
  },
  {
    id: 37,
    slug: `materials`,
    name: `Materials`,
    description: `Covering breakthroughs in next-generation materials, novel composites, nanotechnology, and their industry applications.`,
    count: 3,
  },
  {
    id: 44,
    slug: `devices`,
    name: `Devices`,
    description: `Exploring medical devices, consumer technology, wearable innovations, and hardware shaping everyday life.`,
    count: 2,
  },
  {
    id: 46,
    slug: `digitaltherapeutics`,
    name: `Digital Therapeutics`,
    description: `Highlighting software-driven healthcare solutions, apps, and technologies transforming patient care and treatment.`,
    count: 2,
  },
  {
    id: 53,
    slug: `governance`,
    name: `Government Innovation & Smart Cities`,
    description: `Covering smart governance, urban innovation, digital infrastructure, and forward-looking public initiatives.`,
    count: 2,
  },
  {
    id: 54,
    slug: `health`,
    name: `Health & Wellness`,
    description: `Reporting on precision medicine, wellness technology, longevity science, and innovations redefining health care.`,
    count: 2,
  },
  {
    id: 58,
    slug: `longevity`,
    name: `Longevity & Aging`,
    description: `Investigating advances in aging science, longevity research, lifespan extension, and healthy aging technologies.`,
    count: 2,
  },
  {
    id: 67,
    slug: `transport`,
    name: `Transportation & Autonomous Vehicles`,
    description: `Exploring innovations in mobility, autonomous driving, transportation infrastructure, and next-gen vehicle technology.`,
    count: 2,
  },
  {
    id: 41,
    slug: `culture`,
    name: `Culture & Social Change`,
    description: `Examining the trends, ideas, and movements shaping our global culture and driving societal evolution.`,
    count: 1,
  },
  {
    id: 47,
    slug: `ecosystem`,
    name: `Ecosystem`,
    description: `Insights into innovation ecosystems, startup communities, accelerators, incubators, and collaborative growth strategies.`,
    count: 1,
  },
  {
    id: 49,
    slug: `regulatory`,
    name: `Ethics, Policy & Regulation`,
    description: `Analysis of policy trends, ethical debates, regulatory frameworks, and governance shaping innovation globally.`,
    count: 1,
  },
  {
    id: 50,
    slug: `fintech`,
    name: `Fintech & Financial Innovation`,
    description: `Insights into technology-driven financial services, digital banking, and innovations transforming the financial world.`,
    count: 1,
  },
  {
    id: 55,
    slug: `performance`,
    name: `Human Performance & Enhancement`,
    description: `Exploring technologies and methods enhancing human capabilities, productivity, wellness, and overall performance.`,
    count: 1,
  },
  {
    id: 62,
    slug: `quantum`,
    name: `Quantum Computing`,
    description: `Insights on quantum breakthroughs, emerging technologies, computing power, and revolutionary industry applications.`,
    count: 1,
  },
  {
    id: 65,
    slug: `space`,
    name: `Space Exploration & Aerospace`,
    description: `Tracking developments in aerospace, space travel, satellite technology, and humanity’s journey beyond Earth.`,
    count: 1,
  },
  {
    id: 69,
    slug: `sticky`,
    name: `Sticky`,
    description: ``,
    count: 1,
  },
  {
    id: 40,
    slug: `blockchain`,
    name: `Blockchain & Cryptocurrency`,
    description: `Covering decentralized technologies, digital currencies, blockchain adoption, and their societal implications.`,
    count: 0,
  },
  {
    id: 45,
    slug: `diagnostics`,
    name: `Diagnostics`,
    description: `Covering diagnostic innovations, testing technologies, biomarker research, and precision health breakthroughs.`,
    count: 0,
  },
  {
    id: 105,
    slug: `events`,
    name: `Events`,
    description: `Event highlights.`,
    count: 0,
  },
  {
    id: 51,
    slug: `foodtech`,
    name: `Food Tech`,
    description: `Covering innovations in sustainable agriculture, alternative proteins, food safety technologies, and the future of nutrition.`,
    count: 0,
  },
  {
    id: 38,
    slug: `genetics`,
    name: `Genetics`,
    description: `Insights into genetic breakthroughs, gene-editing tools, and their transformative impacts.`,
    count: 0,
  },
  {
    id: 56,
    slug: `entrepreneurship`,
    name: `Innovation & Entrepreneurship`,
    description: `Showcasing entrepreneurial ventures, innovation ecosystems, startup culture, and ideas shaping the global economy.`,
    count: 0,
  },
  {
    id: 63,
    slug: `robotics`,
    name: `Robotics & Automation`,
    description: `Reporting on robotic technologies, AI-driven automation, human-robot collaboration, and their impacts on industry.`,
    count: 0,
  },
  {
    id: 64,
    slug: `electronics`,
    name: `Semiconductors & Electronics`,
    description: `Deep dives into semiconductor innovations, electronics breakthroughs, chip technology, and future hardware solutions.`,
    count: 0,
  },
  {
    id: 68,
    slug: `invest`,
    name: `Venture Capital & Investing`,
    description: `Analysis of funding trends, startup investing strategies, venture capital insights, and financing innovation.`,
    count: 0,
  },
  {
    id: 52,
    slug: `work`,
    name: `Work & Education`,
    description: `Tracking workplace shifts, educational innovation, remote collaboration, and the skills shaping tomorrow’s workforce.`,
    count: 0,
  },
];

export const categoryBySlug = (slug: string): Category | undefined =>
  categories.find(c => c.slug === slug);
