export interface Tag {
  id: number;
  slug: string;
  name: string;
  count: number;
}

export const tags: Tag[] = [
  {
    id: 76,
    slug: `nuclear`,
    name: `nuclear`,
    count: 7,
  },
  {
    id: 23,
    slug: `technology`,
    name: `Technology`,
    count: 6,
  },
  {
    id: 72,
    slug: `biotech`,
    name: `biotech`,
    count: 4,
  },
  {
    id: 71,
    slug: `defense`,
    name: `defense`,
    count: 4,
  },
  {
    id: 87,
    slug: `sustainability`,
    name: `sustainability`,
    count: 2,
  },
  {
    id: 81,
    slug: `2025`,
    name: `2025`,
    count: 1,
  },
  {
    id: 74,
    slug: `ai`,
    name: `ai`,
    count: 1,
  },
  {
    id: 95,
    slug: `ai-imaging-bundles`,
    name: `ai imaging bundles`,
    count: 1,
  },
  {
    id: 123,
    slug: `ai-optimization-for-operations`,
    name: `AI Optimization for Operations`,
    count: 1,
  },
  {
    id: 103,
    slug: `arab-health-2025`,
    name: `arab health 2025`,
    count: 1,
  },
  {
    id: 73,
    slug: `artificial-intelligence`,
    name: `artificial intelligence`,
    count: 1,
  },
  {
    id: 109,
    slug: `asme-energy-sustainability-2025`,
    name: `ASME Energy & Sustainability 2025`,
    count: 1,
  },
  {
    id: 83,
    slug: `astrophysics`,
    name: `astrophysics`,
    count: 1,
  },
  {
    id: 121,
    slug: `audit-ready-machine-learning`,
    name: `Audit Ready Machine Learning`,
    count: 1,
  },
  {
    id: 125,
    slug: `behind-the-meter-orchestration`,
    name: `Behind the Meter Orchestration`,
    count: 1,
  },
  {
    id: 120,
    slug: `capacity-payments-and-ancillary-services`,
    name: `Capacity Payments and Ancillary Services`,
    count: 1,
  },
  {
    id: 129,
    slug: `climate`,
    name: `climate`,
    count: 1,
  },
  {
    id: 128,
    slug: `climate-tech-execution-mode`,
    name: `Climate Tech Execution Mode`,
    count: 1,
  },
  {
    id: 82,
    slug: `conferences`,
    name: `conferences`,
    count: 1,
  },
  {
    id: 97,
    slug: `cssd-sterilization`,
    name: `cssd sterilization`,
    count: 1,
  },
  {
    id: 85,
    slug: `cybersecurity`,
    name: `cybersecurity`,
    count: 1,
  },
  {
    id: 116,
    slug: `demand-flexibility-and-load-management`,
    name: `Demand Flexibility and Load Management`,
    count: 1,
  },
  {
    id: 104,
    slug: `dubai-health-authority`,
    name: `dubai health authority`,
    count: 1,
  },
  {
    id: 130,
    slug: `energy`,
    name: `energy`,
    count: 1,
  },
  {
    id: 101,
    slug: `gcc-healthcare-procurement`,
    name: `gcc healthcare procurement`,
    count: 1,
  },
  {
    id: 108,
    slug: `grid-interconnection-queues`,
    name: `Grid Interconnection Queues`,
    count: 1,
  },
  {
    id: 89,
    slug: `health`,
    name: `health`,
    count: 1,
  },
  {
    id: 102,
    slug: `healthcare-ai-governance`,
    name: `healthcare ai governance`,
    count: 1,
  },
  {
    id: 75,
    slug: `indonesia`,
    name: `indonesia`,
    count: 1,
  },
  {
    id: 114,
    slug: `industrial-decarbonization`,
    name: `Industrial Decarbonization`,
    count: 1,
  },
  {
    id: 91,
    slug: `infection-control-gcc`,
    name: `infection control gcc`,
    count: 1,
  },
  {
    id: 119,
    slug: `long-duration-energy-storage`,
    name: `Long Duration Energy Storage`,
    count: 1,
  },
  {
    id: 92,
    slug: `malaffi`,
    name: `malaffi`,
    count: 1,
  },
  {
    id: 86,
    slug: `manufacturing`,
    name: `manufacturing`,
    count: 1,
  },
  {
    id: 70,
    slug: `medicine`,
    name: `medicine`,
    count: 1,
  },
  {
    id: 127,
    slug: `model-cards-and-governance`,
    name: `Model Cards and Governance`,
    count: 1,
  },
  {
    id: 99,
    slug: `nabidh`,
    name: `nabidh`,
    count: 1,
  },
  {
    id: 98,
    slug: `on-prem-ai-inference`,
    name: `on-prem ai inference`,
    count: 1,
  },
  {
    id: 96,
    slug: `payer-provider-platforms`,
    name: `payer-provider platforms`,
    count: 1,
  },
  {
    id: 115,
    slug: `peak-shaving-hybrids`,
    name: `Peak Shaving Hybrids`,
    count: 1,
  },
  {
    id: 78,
    slug: `pharma`,
    name: `pharma`,
    count: 1,
  },
  {
    id: 110,
    slug: `process-heat-electrification`,
    name: `Process Heat Electrification`,
    count: 1,
  },
  {
    id: 131,
    slug: `programming`,
    name: `programming`,
    count: 1,
  },
  {
    id: 111,
    slug: `protection-studies-and-nerc-compliance`,
    name: `Protection Studies and NERC Compliance`,
    count: 1,
  },
  {
    id: 84,
    slug: `quantum`,
    name: `quantum`,
    count: 1,
  },
  {
    id: 77,
    slug: `radwastesummit`,
    name: `radwastesummit`,
    count: 1,
  },
  {
    id: 118,
    slug: `resource-adequacy-markets`,
    name: `Resource Adequacy Markets`,
    count: 1,
  },
  {
    id: 124,
    slug: `scada-bms-plant-historians`,
    name: `SCADA BMS Plant Historians`,
    count: 1,
  },
  {
    id: 80,
    slug: `startups`,
    name: `startups`,
    count: 1,
  },
  {
    id: 126,
    slug: `tariff-aware-dispatch`,
    name: `Tariff Aware Dispatch`,
    count: 1,
  },
  {
    id: 113,
    slug: `thermal-storage-and-heat-pumps`,
    name: `Thermal Storage and Heat Pumps`,
    count: 1,
  },
  {
    id: 112,
    slug: `transformer-supply-constraints`,
    name: `Transformer Supply Constraints`,
    count: 1,
  },
  {
    id: 100,
    slug: `uae-data-localization`,
    name: `uae data localization`,
    count: 1,
  },
  {
    id: 93,
    slug: `uae-pdpl`,
    name: `uae pdpl`,
    count: 1,
  },
  {
    id: 122,
    slug: `utility-programs-and-rate-cases`,
    name: `Utility Programs and Rate Cases`,
    count: 1,
  },
  {
    id: 117,
    slug: `waste-heat-recovery`,
    name: `Waste Heat Recovery`,
    count: 1,
  },
  {
    id: 94,
    slug: `whx-dubai`,
    name: `whx dubai`,
    count: 1,
  },
  {
    id: 90,
    slug: `world-health-expo-dubai-2025`,
    name: `world health expo dubai 2025`,
    count: 1,
  },
  {
    id: 106,
    slug: `2025-events`,
    name: `2025 events`,
    count: 0,
  },
  {
    id: 9,
    slug: `3d`,
    name: `3D`,
    count: 0,
  },
  {
    id: 10,
    slug: `art`,
    name: `art`,
    count: 0,
  },
  {
    id: 11,
    slug: `book`,
    name: `Book`,
    count: 0,
  },
  {
    id: 12,
    slug: `branding`,
    name: `Branding`,
    count: 0,
  },
  {
    id: 13,
    slug: `design`,
    name: `Design`,
    count: 0,
  },
  {
    id: 132,
    slug: `devices`,
    name: `devices`,
    count: 0,
  },
  {
    id: 107,
    slug: `events`,
    name: `events`,
    count: 0,
  },
  {
    id: 14,
    slug: `fashion`,
    name: `fashion`,
    count: 0,
  },
  {
    id: 15,
    slug: `lifestyle`,
    name: `lifestyle`,
    count: 0,
  },
  {
    id: 133,
    slug: `logistics`,
    name: `logistics`,
    count: 0,
  },
  {
    id: 16,
    slug: `logo`,
    name: `Logo`,
    count: 0,
  },
  {
    id: 17,
    slug: `magazine`,
    name: `Magazine`,
    count: 0,
  },
  {
    id: 18,
    slug: `music`,
    name: `music`,
    count: 0,
  },
  {
    id: 19,
    slug: `photography`,
    name: `Photography`,
    count: 0,
  },
  {
    id: 20,
    slug: `politics`,
    name: `Politics`,
    count: 0,
  },
  {
    id: 21,
    slug: `sport`,
    name: `Sport`,
    count: 0,
  },
  {
    id: 22,
    slug: `style`,
    name: `style`,
    count: 0,
  },
];

export const tagBySlug = (slug: string): Tag | undefined =>
  tags.find(t => t.slug === slug);
